version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2

    working_directory: /go/src/github.com/akrfjmt/di114514

    steps:
      - checkout
      - run: go test -v ./...
      - run: go get github.com/pierrre/gotestcover
      - run:
          command: |
            if [ "$CODECOV_TOKEN" != "" ]; then
              gotestcover -coverprofile=coverage.txt ./...
              curl -s https://codecov.io/bash | bash -s --
            else
              echo "please specify \$CODECOV_TOKEN"
              echo "https://github.com/cainus/codecov.io/blob/master/README.md#upload-repo-tokens"
            fi
