version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2

    working_directory: /go/src/github.com/akrfjmt/di114514

    steps:
      - checkout
      - run: go test -v -race -coverprofile coverage.txt -covermode=atomic ./...
      - run:
          command: |
            if [ "$CODECOV_TOKEN" != "" ]; then
              curl -s https://codecov.io/bash | bash -s --
            else
              echo "please specify \$CODECOV_TOKEN"
              echo "https://github.com/codecov/codecov-node#upload-repo-tokens"
            fi
      - run:
          command: |
            if [ "$COVERALLS_TOKEN" != "" ]; then
              go get github.com/mattn/goveralls
              goveralls -coverprofile=coverage.txt -covermode=count -service=circle-ci -repotoken $COVERALLS_TOKEN
            else
              echo "please specify \$COVERALLS_TOKEN"
              echo "https://coveralls.io/"
            fi
